name: Auto Deploy to Local Machine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check Node.js version
      run: |
        echo "Node.js version:"
        node --version || echo "Node.js not installed"
        echo "NPM version:"
        npm --version || echo "NPM not installed"

    - name: Install dependencies (if package.json exists)
      run: |
        if [ -f "package.json" ]; then
          echo "Installing dependencies..."
          npm install
        else
          echo "No package.json found, skipping npm install"
        fi

    - name: Build project (if build script exists)
      run: |
        if [ -f "package.json" ] && npm run build --if-present; then
          echo "Build completed successfully"
        else
          echo "No build script found or build not needed"
        fi

    - name: Deploy to local directory
      run: |
        # Tạo thư mục deploy nếu chưa có
        DEPLOY_DIR="$HOME/deployed-apps/demo-playwright"
        mkdir -p "$DEPLOY_DIR"
        
        # Copy files to deploy directory
        echo "Copying files to $DEPLOY_DIR"
        cp -r * "$DEPLOY_DIR/" 2>/dev/null || true
        
        echo "Deployment completed to: $DEPLOY_DIR"
        echo "Files deployed:"
        ls -la "$DEPLOY_DIR"

    - name: Start local server (optional)
      run: |
        # Kiểm tra nếu có server đang chạy trên port 8080
        if lsof -ti:8080; then
          echo "Stopping existing server on port 8080"
          kill $(lsof -ti:8080) || true
          sleep 2
        fi
        
        # Khởi động server đơn giản cho static files
        cd "$HOME/deployed-apps/demo-playwright"
        echo "Starting local server on http://localhost:8080"
        nohup python3 -m http.server 8080 > server.log 2>&1 &
        
        # Đợi server khởi động
        sleep 3
        
        # Kiểm tra server
        if curl -s http://localhost:8080 > /dev/null; then
          echo "✅ Server started successfully at http://localhost:8080"
        else
          echo "❌ Failed to start server"
        fi

    - name: Cleanup
      run: |
        echo "Cleaning up temporary files..."
        # Xóa các file tạm nếu có
        rm -f *.tmp 2>/dev/null || true
        echo "✅ Deployment process completed!"
